name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_linux_x64:
    name: Build and run (Linux x64)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Test
        run: nix develop -c bash -c zig build test
  build_macos_64:
    name: Build and run (macOS x64)
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Test
        run: nix develop -c bash -c zig build test
